services:

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - blog
    volumes:
      - blog-volume:/data/db
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - blog
    depends_on:
      - mongodb
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - blog

networks:
  blog:
    driver: bridge

volumes:
  blog-volume:
    driver: local
