# Generated by Django 4.1.13 on 2024-12-28 14:12

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='input_field_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('label', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=2000)),
                ('language', models.TextField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='input_field_images/')),
            ],
        ),
    ]
